students/k3339/Berulava_Leon/laba/firm/firm/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from tour.views import Index, addTour, tour_detail, basket_add, basket_view, basket_remove, confirm_booking, booking_views

urlpatterns = [
    path("admin/", admin.site.urls), 
    path('', Index, name="Index"),
    path('page/<int:page>', Index, name='paginator'),
    path("users/", include('users.urls', namespace='users')),
    path('addtour/', addTour, name="addTour"),
    path('tour/<int:tour_id>/', tour_detail, name='tour_detail'),
    path('baskets/add/<int:tour_id>/', basket_add, name='basket_add'),
    path('baskets/remove/<int:basket_id>/', basket_remove, name='basket_remove'),
    path('basket/', basket_view, name='basket'),
    path('basket/confirm/', confirm_booking, name='confirm_booking'),
    path('bookings/', booking_views, name='booking_views'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

students/k3339/Berulava_Leon/laba/firm/users/urls.py
from django.urls import path, include
from users.views import login, registration, logout

app_name = 'users'

urlpatterns = [
    path('login/', login, name='login'),
    path('registration/', registration, name='registration'),
    path('logout/', logout, name='logout')
]

students/k3339/Berulava_Leon/laba/firm/tour/models.py
from django.db import models
from django.contrib.auth import get_user_model

# Получение кастомной модели пользователя
User = get_user_model()

class Tour(models.Model):
    name = models.CharField(max_length=255)
    agency = models.CharField(max_length=255)
    description = models.TextField()
    start_date = models.DateField()
    end_date = models.DateField()
    payment_terms = models.TextField()
    price = models.DecimalField(max_digits=16, decimal_places=2, default=0.00)

    def __str__(self):
        return self.name

class Review(models.Model):
    tour = models.ForeignKey(Tour, on_delete=models.CASCADE, related_name='reviews')  # Привязываем к туру
    user = models.ForeignKey(User, on_delete=models.CASCADE)  # Привязываем к пользователю
    rating = models.PositiveIntegerField()  # Оценка от 1 до 5
    comment = models.TextField()  # Текст отзыва
    created_at = models.DateTimeField(auto_now_add=True)  # Дата создания отзыва

    def __str__(self):
        return f"Review for {self.tour.name} by {self.user.username}"

class Basket(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    tour = models.ForeignKey(to=Tour, on_delete=models.CASCADE)
    quantity = models.PositiveSmallIntegerField(default=0)
    created_timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.tour.name}"

class Booking(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    tour = models.ForeignKey(Tour, on_delete=models.CASCADE)
    quantity = models.PositiveSmallIntegerField(default=1)
    is_approved = models.BooleanField(default=False)  # Статус подтверждения
    created_at = models.DateTimeField(auto_now_add=True)  # Время создания записи

    def total_price(self):
        return self.quantity * self.tour.price

    def __str__(self):
        return f"Booking: {self.tour.name} by {self.user.username}"

students/k3339/Berulava_Leon/laba/firm/tour/forms.py
from django import forms
from tour.models import Tour, Review

class TourForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-group',
        'placeholder': 'Введите название тура'
    }))
    agency = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-group',
        'placeholder': 'Введите название вашего агенства'
    }))
    description = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-group',
        'placeholder': 'Введите описание вашего тура'
    }))
    start_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    end_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    payment_terms = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-group',
        'placeholder': 'Введите условия оплаты'
    }))
    price = forms.DecimalField(max_digits=10, decimal_places=2, min_value=0, widget=forms.NumberInput(attrs={
        'class': 'form-group',
        'placeholder': 'Введите цену'
    }))

    class Meta:
        model = Tour
        fields = ('name', 'agency', 'description', 'start_date', 'end_date', 'payment_terms', 'price')

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['rating', 'comment']
        widgets = {
            'rating': forms.NumberInput(attrs={'min': 1, 'max': 5, 'placeholder': 'Оценка от 1 до 5'}),
            'comment': forms.Textarea(attrs={'placeholder': 'Напишите ваш отзыв'}),
        }

students/k3339/Berulava_Leon/laba/firm/tour/views.py
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404
from django.urls import reverse
from .models import Tour, Basket, Booking
from django.views.decorators.csrf import csrf_protect
from .forms import TourForm, ReviewForm
from django.core.paginator import Paginator

# Create your views here.

def Index(request, page=1):
    tours = Tour.objects.all()
    paginator = Paginator(tours, 3)
    tours_paginator = paginator.page(page)
    context = {
        'tours': tours_paginator
    }
    return render(request, 'tour/index.html', context)

@csrf_protect
def addTour(request):
    if request.method == "POST":
        form = TourForm(request.POST)
        if form.is_valid():
            tour = form.save(commit=False)  # Используем переменную 'tour', чтобы избежать конфликта с моделью
            tour.save()  # Сохраняем объект в базе данных
            return HttpResponseRedirect(reverse('Index'))
        else:
            print("Ошибки формы:", form.errors)
    else:
        form = TourForm()

    context = {'form': form}
    return render(request, 'tour/addTour.html', context)

def tour_detail(request, tour_id):
    tour = get_object_or_404(Tour, id=tour_id)
    reviews = tour.reviews.all()  # Получаем все отзывы для данного тура

    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.tour = tour  # Привязываем отзыв к конкретному туру
            review.user = request.user  # Привязываем отзыв к текущему пользователю
            review.save()
            return HttpResponseRedirect(reverse('tour_detail', args=[tour.id]))
    else:
        form = ReviewForm()

    context = {
        'tour': tour,
        'reviews': reviews,
        'form': form,
    }
    return render(request, 'tour/abouttour.html', context)

def basket_add(request, tour_id):
    tour = Tour.objects.get(id=tour_id)
    baskets = Basket.objects.filter(user=request.user, tour=tour)

    if not baskets.exists():
        Basket.objects.create(user=request.user, tour=tour, quantity=1)
    else:
        basket = baskets.first()
        basket.quantity += 1
        basket.save()

    return HttpResponseRedirect(request.META['HTTP_REFERER'])

def basket_remove(request, basket_id):
    basket = Basket.objects.get(id=basket_id)
    basket.delete()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])

def basket_view(request):
    baskets = Basket.objects.filter(user=request.user)
    total_price = sum(basket.tour.price * basket.quantity for basket in baskets)

    context = {
        'baskets': baskets,
        'total_price': total_price,
    }
    return render(request, 'tour/basket.html', context)


def confirm_booking(request):
    baskets = Basket.objects.filter(user=request.user)

    for basket in baskets:
        # Создаем бронирование для каждого элемента корзины
        Booking.objects.create(
            user=request.user,
            tour=basket.tour,
            quantity=basket.quantity
        )
        basket.delete()  # Удаляем элемент из корзины после переноса

    return HttpResponseRedirect(request.META['HTTP_REFERER'])

def booking_views(request):
    bookings = Booking.objects.all()
    baskets = Basket.objects.filter(user=request.user)
    total_price = sum(basket.tour.price * basket.quantity for basket in baskets)

    context = {
        'bookings': bookings
    }
    return render(request, 'tour/bookings.html', context)

students/k3339/Berulava_Leon/laba/firm/tour/templates/tour/abouttour.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ tour.name }}</title>
    <link rel="stylesheet" href="{% static 'tours/css/abouttour.css' %}">
    <link rel="stylesheet" href="{% static 'tours/css/style.css' %}">
</head>
<body>
    <header>
        <nav class="navbar">
            <div class="navbar-container">
                <a href="{% url 'Index' %}" class="navbar-logo">TravelAgency</a>
                <ul class="navbar-links">
                    <li><a href="{% url 'Index' %}">Главная</a></li>
                    <li><a href="{% url 'basket' %}">Корзина</a></li>
                    {% if user.is_authenticated %}
                        {% if user.is_superuser %}
                            <li><a href="{% url 'addTour' %}">Добавить свой тур</a></li>
                        {% endif %}
                        <li><a href="#">Личный кабинет</a></li>
                        <li><a href="{% url 'users:logout' %}">Выйти</a></li>
                    {% else %}
                        <li><a href="{% url 'users:login' %}">Вход</a></li>
                        <li><a href="{% url 'users:registration' %}">Регистрация</a></li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>

    <div class="container">
        <div class="tour-details">
            <h1>{{ tour.name }}</h1>
            <p class="tour-agency">Турагентство: <strong>{{ tour.agency }}</strong></p>
            <p class="tour-description">Описание: {{ tour.description }}</p>
            <p class="tour-dates">Период проведения: с {{ tour.start_date }} по {{ tour.end_date }}</p>
            <p class="tour-payment-terms">Условия оплаты: {{ tour.payment_terms }}</p>
            <p class="tour-price">Цена: <strong>{{ tour.price }} руб.</strong></p>
            <a href="{% url 'basket_add' tour.id %}" class="btn-book">Забронировать тур</a>
        </div>
        <div class="reviews-section">
            <h2>Отзывы</h2>
            {% if reviews %}
                {% for review in reviews %}
                    <div class="review">
                        <p><strong>{{ review.user.first_name }}</strong> ({{ review.created_at|date:"d.m.Y" }})</p>
                        <p>Оценка: {{ review.rating }}</p>
                        <p>{{ review.comment }}</p>
                    </div>
                {% endfor %}
            {% else %}
                <p>Отзывов пока нет. Будьте первым!</p>
            {% endif %}
        </div>

        {% if user.is_authenticated %}
            <div class="review-form">
                <h3>Добавить отзыв</h3>
                <form method="POST">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn-submit">Отправить</button>
                </form>
            </div>
        {% else %}
            <p>Войдите в аккаунт, чтобы оставить отзыв.</p>
        {% endif %}
    </div>



    <footer>
        <p>&copy; 2024 TravelAgency. Все права защищены.</p>
    </footer>
</body>
</html>

students/k3339/Berulava_Leon/laba/firm/tour/templates/tour/addTour.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Добавить Тур</title>
    <link rel="stylesheet" href="{% static 'tours/css/addtour.css' %}">
</head>
<body>
    <div class="add-tour-container">
        <h1>Добавить Новый Тур</h1>
        <form action="{% url 'addTour' %}" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="{{ form.name.id_for_label }}">Название тура:</label>
                {{ form.name }}
            </div>

            <div class="form-group">
                <label for="{{ form.agency.id_for_label }}">Агентство:</label>
                {{ form.agency }}
            </div>

            <div class="form-group">
                <label for="{{ form.description.id_for_label }}">Описание:</label>
                {{ form.description }}
            </div>

            <div class="form-group">
                <label for="{{ form.start_date.id_for_label }}">Дата начала:</label>
                {{ form.start_date }}
            </div>

            <div class="form-group">
                <label for="{{ form.end_date.id_for_label }}">Дата конца:</label>
                {{ form.end_date }}
            </div>

            <div class="form-group">
                <label for="{{ form.payment_terms.id_for_label }}">Условия оплаты:</label>
                {{ form.payment_terms }}
            </div>

             <div class="form-group">
                <label for="{{ form.price.id_for_label }}">Цена</label>
                {{ form.price }}
            </div>

            <button type="submit">Добавить Тур</button>
        </form>
    </div>
</body>
</html>

students/k3339/Berulava_Leon/laba/firm/tour/templates/tour/basket.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Корзина</title>
    <link rel="stylesheet" href="{% static 'tours/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'tours/css/basket.css' %}">
</head>
<body>
    <header>
        <nav class="navbar">
            <div class="navbar-container">
                <a href="{% url 'Index' %}" class="navbar-logo">TravelAgency</a>
                <ul class="navbar-links">
                    <li><a href="{% url 'Index' %}">Главная</a></li>
                    <li><a href="{% url 'basket' %}">Корзина</a></li>
                    {% if user.is_authenticated %}
                        {% if user.is_superuser %}
                            <li><a href="{% url 'addTour' %}">Добавить свой тур</a></li>
                        {% endif %}
                        <li><a href="#">Личный кабинет</a></li>
                        <li><a href="{% url 'users:logout' %}">Выйти</a></li>
                    {% else %}
                        <li><a href="{% url 'users:login' %}">Вход</a></li>
                        <li><a href="{% url 'users:registration' %}">Регистрация</a></li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>
    <div class="container">
        <h1>Корзина туров</h1>
        {% if baskets %}
            <table>
                <thead>
                    <tr>
                        <th>Тур</th>
                        <th>Количество</th>
                        <th>Цена</th>
                        <th>Количество</th>
                        <th>Действия</th>
                    </tr>
                </thead>
                <tbody>
                    {% for basket in baskets %}
                    <tr>
                        <td>{{ basket.tour.name }}</td>
                        <td>{{ basket.quantity }}</td>
                        <td>{{ basket.tour.price }} руб.</td>
                        <td>{{ basket.quantity|floatformat:0 }}</td>
                        <td>
                            <a href="{% url 'basket_remove' basket.id %}">Удалить</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            <p><strong>Общая сумма:</strong> {{ total_price }} руб.</p>
        {% else %}
            <p>Ваша корзина пуста.</p>
        {% endif %}

        <form action="{% url 'confirm_booking' %}" method="POST">
        {% csrf_token %}
            <button type="submit" class="btn-confirm">Подтвердить покупку</button>
        </form>

</form>

    </div>


</body>
</html>

students/k3339/Berulava_Leon/laba/firm/tour/templates/tour/bookings.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Подтвержденные бронирования</title>
</head>
<body>
    <h1>Подтвержденные бронирования</h1>
    {% if bookings %}
        <table>
            <thead>
                <tr>
                    <th>Название тура</th>
                    <th>Количество</th>
                    <th>Цена за единицу</th>
                    <th>Общая цена</th>
                </tr>
            </thead>
            <tbody>
                {% for booking in bookings %}
                    <tr>
                        <td>{{ booking.user.username }}</td>
                        <td>{{ booking.tour.name }}</td>
                        <td>{{ booking.quantity }}</td>
                        <td>{{ booking.tour.price }}</td>
                        <td>{{ booking.total_price }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <p><strong>Итоговая сумма:</strong> {{ total_price }} руб.</p>
    {% else %}
        <p>Нет подтвержденных бронирований.</p>
    {% endif %}
</body>
</html>

students/k3339/Berulava_Leon/laba/firm/tour/templates/tour/index.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Список туров</title>
    <link rel="stylesheet" href="{% static 'tours/css/style.css' %}?v=3.0">
</head>
<body>

<!-- Навигационная панель -->
    <header>
        <nav class="navbar">
            <div class="navbar-container">
                <a href="{% url 'Index' %}" class="navbar-logo">TravelAgency</a>
                <ul class="navbar-links">
                    <li><a href="{% url 'Index' %}">Главная</a></li>
                    <li><a href="{% url 'basket' %}">Корзина</a></li>
                    {% if user.is_authenticated %}
                        {% if user.is_superuser %}
                            <li><a href="{% url 'addTour' %}">Добавить свой тур</a></li>
                        {% endif %}
                        <li><a href="#">Личный кабинет</a></li>
                        <li><a href="{% url 'users:logout' %}">Выйти</a></li>
                    {% else %}
                        <li><a href="{% url 'users:login' %}">Вход</a></li>
                        <li><a href="{% url 'users:registration' %}">Регистрация</a></li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>


    <div class="container">
        <h1>Список туров</h1>
        {% for tour in tours %}
            <div class="tour-card">
                <h2 class="tour-name">{{ tour.name }}</h2>
                <p class="tour-agency">{{ tour.agency }}</p>
                <p class="tour-description">{{ tour.description }}</p>
                <p class="tour-dates">Период проведения: {{ tour.start_date }} по {{ tour.end_date }}</p>
                <p class="tour-payment-terms">{{ tour.payment_terms }}</p>
                <p class="tour-price">Цена: {{ tour.price }} руб.</p>
                <a href="{% url 'tour_detail' tour.id %}" class="btn btn-details">Подробнее</a>
                <a href="{% url 'basket_add' tour.id %}"> Отправить в корзину </a>
            </div>
        {% endfor %}

        <div class="pagination">
            <button class="pagination-btn prev {% if not tours.has_previous %}disabled{% endif %}"
                    {% if tours.has_previous %}onclick="location.href='{% url 'paginator' tours.previous_page_number %}'"{% endif %}>
                &laquo; Назад
            </button>
            <div class="pagination-pages">
                {% for page in tours.paginator.page_range %}
                    {% if page == 1 or page == tours.paginator.num_pages or page >= tours.number|add:"-2" and page <= tours.number|add:"2" %}
                        <a href="{% url 'paginator' page %}" class="pagination-btn
                            {% if page == tours.number %}active{% endif %}">
                            {{ page }}
                        </a>
                    {% elif page == tours.number|add:"-3" or page == tours.number|add:"3" %}
                        <span class="pagination-dots">...</span>
                    {% endif %}
                {% endfor %}
            </div>
            <button class="pagination-btn next {% if not tours.has_next %}disabled{% endif %}"
                    {% if tours.has_next %}onclick="location.href='{% url 'paginator' tours.next_page_number %}'"{% endif %}>
                Вперед &raquo;
            </button>
</div>

    </div>
</body>
</html>